// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfwgygsfwgpikhkpmbih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmd2d5Z3Nmd2dwaWtoa3BtYmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mzg4NzMsImV4cCI6MjA2NzAxNDg3M30.LtvVznOP0gmdwEsBLMy6xlBaCqXfbBHVM1sBcDAncwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});